### Libraries imported

In [4]:
# needed libraries imported
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt

### Sample Dataset created

In [38]:
# A sample dataset was created

data = {
    "Student Name ": ["declan", "Roy", "Calvin", "Roy", None],
    "Age ": [25, 23, 20, None, 150],
    "Score ": [85, 90, 84, 88, 999]
    }

# The dataset was converted into a DataFrame
df = pd.DataFrame(data)

# The DataFrame was saved as a CSV file
df.to_csv("student_data.csv", index=False)

print(df)

  Student Name    Age   Score
0        declan   25.0      85
1           Roy   23.0      90
2        Calvin   20.0      84
3           Roy    NaN      88
4          None  150.0     999

### Cleaning Function created

In [39]:
# A function was created to clean any CSV file

def clean_data(file_path):

# The CSV file was read

 df = pd.read_csv("student_data.csv")

df

  Student Name    Age   Score
0        declan   25.0      85
1           Roy   23.0      90
2        Calvin   20.0      84
3           Roy    NaN      88
4          None  150.0     999

In [40]:
# Column names were cleaned
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

df.columns

Index(['student_name', 'age', 'score'], dtype='object')

In [ ]:
# student name was fixed with
df["student_name"] =  df["student_name"].str.title().replace("Cyri", "John")

# Duplicate rows were removed
df = df.drop_duplicates(subset=["student_name"])

print(df)

In [50]:
# Missing values in Age were replaced with 0
df["age"] = df["age"].fillna(0)

# Missing values in Score were replaced with 0
df["score"] = df["score"].fillna(0)

# Missing values in Student Name were replaced with Unknown
df["student_name"] = df["student_name"].fillna("Unknown")

df

  student_name    age  score
0       Declan   25.0     85
1        Cyril   23.0     90
2       Calvin   20.0     84
4      Unknown  150.0    999

In [34]:
 # Outliers in Age were removed
df = df[df["age"] <= 100]

# Outliers in Score were removed
df = df[df["score"] <= 100]

print(df)

  student_name   age  score
0       Declan  25.0     85
1          Roy  23.0     90
2       Calvin  20.0     84

In [27]:
 # The cleaned dataset was saved
df.to_csv("cleaned_student_data.csv", index=False)